"""adding authentication classmethod to user model

Revision ID: 344e422c4b78
Revises: 5bff6e2bffab
Create Date: 2017-12-06 09:14:38.089358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344e422c4b78'
down_revision = '5bff6e2bffab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.Text(), nullable=True))
    op.drop_column('users', 'frst_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('frst_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
