"""adding authentication classmethod to user model

Revision ID: 5bff6e2bffab
Revises: 6a231b2d9f8e
Create Date: 2017-12-06 09:13:43.483243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bff6e2bffab'
down_revision = '6a231b2d9f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('frst_name', sa.Text(), nullable=True))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'frst_name')
    # ### end Alembic commands ###
